/**
 * Course Intelligence repository.
 *
 * Handles persistence of calculated course intelligence metrics.
 * Course intelligence is generated by the Course Intelligence Engine
 * and read by Tournament pages, AI features, DFS tools, and analytics.
 */

import type { PrismaClient, CourseIntelligence as CourseIntelligenceRecord } from '@/lib/generated/prisma/client'
import prismaClient from '@/lib/prisma'
import type { CourseIntelligence } from '@/lib/course-intelligence/types'

/**
 * Input for creating/updating course intelligence.
 */
export interface CourseIntelligenceInput {
  courseId: string
  overallDifficultyScore: number
  overallDifficultyStars: number
  drivingImportanceScore: number
  drivingImportanceStars: number
  approachImportanceScore: number
  approachImportanceStars: number
  shortGameImportanceScore: number
  shortGameImportanceStars: number
  puttingImportanceScore: number
  puttingImportanceStars: number
  windSensitivityScore: number
  windSensitivityStars: number
  penaltySeverityScore: number
  penaltySeverityStars: number
  birdiePotentialScore: number
  birdiePotentialStars: number
  scoringVolatilityScore: number
  scoringVolatilityStars: number
  calculationVersion?: string
}

export function getCourseIntelligenceRepository(prisma: PrismaClient = prismaClient) {
  return {
    /**
     * Find course intelligence by course ID.
     */
    async findByCourseId(courseId: string): Promise<CourseIntelligenceRecord | null> {
      try {
        return await prisma.courseIntelligence.findUnique({
          where: { courseId },
        })
      } catch (error) {
        console.error(`[v0] CourseIntelligenceRepository.findByCourseId failed for courseId: ${courseId}`, error)
        return null
      }
    },

    /**
     * Create new course intelligence record.
     */
    async create(input: CourseIntelligenceInput): Promise<CourseIntelligenceRecord> {
      try {
        return await prisma.courseIntelligence.create({
          data: {
            courseId: input.courseId,
            overallDifficultyScore: input.overallDifficultyScore,
            overallDifficultyStars: input.overallDifficultyStars,
            drivingImportanceScore: input.drivingImportanceScore,
            drivingImportanceStars: input.drivingImportanceStars,
            approachImportanceScore: input.approachImportanceScore,
            approachImportanceStars: input.approachImportanceStars,
            shortGameImportanceScore: input.shortGameImportanceScore,
            shortGameImportanceStars: input.shortGameImportanceStars,
            puttingImportanceScore: input.puttingImportanceScore,
            puttingImportanceStars: input.puttingImportanceStars,
            windSensitivityScore: input.windSensitivityScore,
            windSensitivityStars: input.windSensitivityStars,
            penaltySeverityScore: input.penaltySeverityScore,
            penaltySeverityStars: input.penaltySeverityStars,
            birdiePotentialScore: input.birdiePotentialScore,
            birdiePotentialStars: input.birdiePotentialStars,
            scoringVolatilityScore: input.scoringVolatilityScore,
            scoringVolatilityStars: input.scoringVolatilityStars,
            calculationVersion: input.calculationVersion || 'v1',
            calculatedAt: new Date(),
          },
        })
      } catch (error) {
        console.error(`[v0] CourseIntelligenceRepository.create failed for courseId: ${input.courseId}`, error)
        throw error
      }
    },

    /**
     * Update existing course intelligence record.
     */
    async update(
      courseId: string,
      input: Partial<CourseIntelligenceInput>,
    ): Promise<CourseIntelligenceRecord> {
      const updateData: Record<string, any> = {}

      if (input.overallDifficultyScore !== undefined) updateData.overallDifficultyScore = input.overallDifficultyScore
      if (input.overallDifficultyStars !== undefined) updateData.overallDifficultyStars = input.overallDifficultyStars
      if (input.drivingImportanceScore !== undefined) updateData.drivingImportanceScore = input.drivingImportanceScore
      if (input.drivingImportanceStars !== undefined) updateData.drivingImportanceStars = input.drivingImportanceStars
      if (input.approachImportanceScore !== undefined) updateData.approachImportanceScore = input.approachImportanceScore
      if (input.approachImportanceStars !== undefined) updateData.approachImportanceStars = input.approachImportanceStars
      if (input.shortGameImportanceScore !== undefined) updateData.shortGameImportanceScore = input.shortGameImportanceScore
      if (input.shortGameImportanceStars !== undefined) updateData.shortGameImportanceStars = input.shortGameImportanceStars
      if (input.puttingImportanceScore !== undefined) updateData.puttingImportanceScore = input.puttingImportanceScore
      if (input.puttingImportanceStars !== undefined) updateData.puttingImportanceStars = input.puttingImportanceStars
      if (input.windSensitivityScore !== undefined) updateData.windSensitivityScore = input.windSensitivityScore
      if (input.windSensitivityStars !== undefined) updateData.windSensitivityStars = input.windSensitivityStars
      if (input.penaltySeverityScore !== undefined) updateData.penaltySeverityScore = input.penaltySeverityScore
      if (input.penaltySeverityStars !== undefined) updateData.penaltySeverityStars = input.penaltySeverityStars
      if (input.birdiePotentialScore !== undefined) updateData.birdiePotentialScore = input.birdiePotentialScore
      if (input.birdiePotentialStars !== undefined) updateData.birdiePotentialStars = input.birdiePotentialStars
      if (input.scoringVolatilityScore !== undefined) updateData.scoringVolatilityScore = input.scoringVolatilityScore
      if (input.scoringVolatilityStars !== undefined) updateData.scoringVolatilityStars = input.scoringVolatilityStars

      updateData.calculatedAt = new Date()

      return await prisma.courseIntelligence.update({
        where: { courseId },
        data: updateData,
      })
    },

    /**
     * Upsert: create if not exists, update if exists.
     */
    async upsert(input: CourseIntelligenceInput): Promise<CourseIntelligenceRecord> {
      try {
        return await prisma.courseIntelligence.upsert({
          where: { courseId: input.courseId },
          create: {
            courseId: input.courseId,
            overallDifficultyScore: input.overallDifficultyScore,
            overallDifficultyStars: input.overallDifficultyStars,
            drivingImportanceScore: input.drivingImportanceScore,
            drivingImportanceStars: input.drivingImportanceStars,
            approachImportanceScore: input.approachImportanceScore,
            approachImportanceStars: input.approachImportanceStars,
            shortGameImportanceScore: input.shortGameImportanceScore,
            shortGameImportanceStars: input.shortGameImportanceStars,
            puttingImportanceScore: input.puttingImportanceScore,
            puttingImportanceStars: input.puttingImportanceStars,
            windSensitivityScore: input.windSensitivityScore,
            windSensitivityStars: input.windSensitivityStars,
            penaltySeverityScore: input.penaltySeverityScore,
            penaltySeverityStars: input.penaltySeverityStars,
            birdiePotentialScore: input.birdiePotentialScore,
            birdiePotentialStars: input.birdiePotentialStars,
            scoringVolatilityScore: input.scoringVolatilityScore,
            scoringVolatilityStars: input.scoringVolatilityStars,
            calculationVersion: input.calculationVersion || 'v1',
            calculatedAt: new Date(),
          },
          update: {
            overallDifficultyScore: input.overallDifficultyScore,
            overallDifficultyStars: input.overallDifficultyStars,
            drivingImportanceScore: input.drivingImportanceScore,
            drivingImportanceStars: input.drivingImportanceStars,
            approachImportanceScore: input.approachImportanceScore,
            approachImportanceStars: input.approachImportanceStars,
            shortGameImportanceScore: input.shortGameImportanceScore,
            shortGameImportanceStars: input.shortGameImportanceStars,
            puttingImportanceScore: input.puttingImportanceScore,
            puttingImportanceStars: input.puttingImportanceStars,
            windSensitivityScore: input.windSensitivityScore,
            windSensitivityStars: input.windSensitivityStars,
            penaltySeverityScore: input.penaltySeverityScore,
            penaltySeverityStars: input.penaltySeverityStars,
            birdiePotentialScore: input.birdiePotentialScore,
            birdiePotentialStars: input.birdiePotentialStars,
            scoringVolatilityScore: input.scoringVolatilityScore,
            scoringVolatilityStars: input.scoringVolatilityStars,
            calculationVersion: input.calculationVersion || 'v1',
            calculatedAt: new Date(),
          },
        })
      } catch (error) {
        console.error(`[v0] CourseIntelligenceRepository.upsert failed for courseId: ${input.courseId}`, error)
        throw error
      }
    },

    /**
     * Delete course intelligence record.
     */
    async delete(courseId: string): Promise<boolean> {
      try {
        await prisma.courseIntelligence.delete({
          where: { courseId },
        })
        return true
      } catch (error) {
        console.error(`[v0] CourseIntelligenceRepository.delete failed for courseId: ${courseId}`, error)
        return false
      }
    },
  }
}

export type CourseIntelligenceRepository = ReturnType<typeof getCourseIntelligenceRepository>
