import type { DataProvider } from "./types"

/**
 * Provider configuration for all tables in the platform.
 * Maps table names to their data provider source.
 */
export const PROVIDER_CONFIG: Record<string, DataProvider> = {
  // SportsDataIO tables
  tournaments: "sportsdataio",
  tournament_courses: "sportsdataio",
  tournament_fields: "sportsdataio",
  tournament_rounds: "sportsdataio",
  tournament_results: "sportsdataio",
  tournament_player_fields: "sportsdataio",
  players: "sportsdataio",
  player_tour_histories: "sportsdataio",
  player_season_statistics: "sportsdataio",
  player_rounds: "sportsdataio",
  player_rankings: "sportsdataio",
  player_statistics: "sportsdataio",
  player_fantasy_projections: "sportsdataio",
  news_articles: "sportsdataio",
  betting_events: "sportsdataio",
  betting_markets: "sportsdataio",
  betting_outcomes: "sportsdataio",
  fantasy_projections: "sportsdataio",
  dfs_salaries: "sportsdataio",

  // GolfCourseAPI tables
  courses: "golfcourseapi",
  course_details: "golfcourseapi",
  course_addresses: "golfcourseapi",
  course_coordinates: "golfcourseapi",
  course_specifications: "golfcourseapi",
  course_metadata: "golfcourseapi",
  course_holes: "golfcourseapi",
  course_tees: "golfcourseapi",
  course_characteristics: "golfcourseapi",
  tee_hole_yardages: "golfcourseapi",
  playing_conditions: "golfcourseapi",

  // The Odds API tables
  odds_events: "multiple",
  odds_quotes: "multiple",

  // Multiple provider tables
  tournament_course_mappings: "multiple",

  // Reference/System tables
  tours: "internal",
  seasons: "internal",
  nationalities: "internal",
  rounds: "internal",
  round_statistics: "internal",

  // Internal/Generated tables
  course_intelligence: "internal",
  player_intelligence: "internal",
  tournament_intelligence: "internal",
  golfer_ratings: "internal",
  ai_insights: "internal",
  simulations: "internal",
  optimizer_results: "internal",

  // Auth/Application tables
  users: "internal",
  profiles: "internal",
  subscriptions: "internal",
  sessions: "internal",
  accounts: "internal",
  verifications: "internal",

  // User-generated content
  user_favorites: "internal",
  saved_lineups: "internal",

  // Operations
  import_runs: "internal",
  weather_snapshots: "multiple",
  weather_periods: "multiple",
  audit_logs: "internal",
}

/** Provider display information for UI rendering. */
export interface ProviderInfo {
  label: string
  badge: string
  tooltip: string
  color: string
}

export const PROVIDER_INFO: Record<DataProvider, ProviderInfo> = {
  sportsdataio: {
    label: "SportsDataIO",
    badge: "🟦",
    tooltip: "Tournament, player, fantasy, scoring, betting, and schedule data.",
    color: "bg-blue-500/12 text-blue-600 dark:text-blue-400",
  },
  golfcourseapi: {
    label: "GolfCourseAPI",
    badge: "🟩",
    tooltip: "Course layouts, holes, tees, yardages, coordinates, and course metadata.",
    color: "bg-green-500/12 text-green-600 dark:text-green-400",
  },
  internal: {
    label: "Internal",
    badge: "🟨",
    tooltip: "Generated by CaddieIQ.",
    color: "bg-amber-500/12 text-amber-600 dark:text-amber-400",
  },
  multiple: {
    label: "Multiple Providers",
    badge: "🟪",
    tooltip: "Data is merged from SportsDataIO and GolfCourseAPI.",
    color: "bg-purple-500/12 text-purple-600 dark:text-purple-400",
  },
}

/**
 * Get the provider for a given table name.
 * Falls back to "internal" if not explicitly configured.
 */
export function getProviderForTable(tableName: string): DataProvider {
  return PROVIDER_CONFIG[tableName] ?? "internal"
}

/**
 * Get the display info for a provider.
 */
export function getProviderInfo(provider: DataProvider): ProviderInfo {
  return PROVIDER_INFO[provider]
}
