import prisma from '@/lib/prisma'

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const tournamentId = searchParams.get('id')

  if (!tournamentId) {
    return Response.json({ error: 'Tournament ID required' }, { status: 400 })
  }

  try {
    const tournament = await prisma.tournament.findUnique({
      where: { id: tournamentId },
      include: {
        course: true,
        winner: true,
        matchScores: {
          take: 100,
          orderBy: { position: 'asc' },
        },
        dfsContests: { take: 10 },
        weatherSnapshots: { take: 10 },
        oddsQuotes: { take: 20 },
      },
    })

    if (!tournament) {
      return Response.json({ error: 'Tournament not found' }, { status: 404 })
    }

    // Calculate tournament metrics
    const totalPlayers = tournament.matchScores?.length || 0
    const avgScore =
      tournament.matchScores?.reduce((sum, m) => sum + (m.totalScore || 0), 0) /
        totalPlayers || 0
    const courseRating = tournament.course?.rating || 72
    const difficulty =
      avgScore > courseRating + 2 ? 'Hard' : avgScore > courseRating ? 'Medium' : 'Easy'

    // Calculate ownership concentration
    const dfsOwnership = await prisma.dfsPlayerOwnership.findMany({
      where: {
        dfsContest: {
          tournament_id: tournamentId,
        },
      },
      select: { ownershipPercentage: true },
      take: 100,
    })

    const avgOwnership =
      dfsOwnership.reduce((sum, o) => sum + (o.ownershipPercentage || 0), 0) /
        (dfsOwnership.length || 1) || 0
    const maxOwnership = Math.max(...(dfsOwnership.map((o) => o.ownershipPercentage || 0) || [0]))
    const ownershipConcentration = maxOwnership > 30 ? 85 : maxOwnership > 15 ? 60 : 35

    // Get weather data
    const weatherData = tournament.weatherSnapshots?.[0]
    const weatherRisk = weatherData?.windSpeed ?? 0 > 15 ? 'High' : weatherData?.windSpeed ?? 0 > 10 ? 'Medium' : 'Low'

    // Calculate slate volatility
    const projectionVariance = tournament.matchScores ? calculateVariance(tournament.matchScores.map((m) => m.totalScore || 0)) : 0
    const slateVolatility = projectionVariance > 10 ? 'High' : projectionVariance > 5 ? 'Medium' : 'Low'

    // AI recommendations (mock data - would be generated by AI in production)
    const recommendations = {
      tournamentRating: 7.5,
      difficulty,
      weatherRisk,
      ownershipConcentration,
      slateVolatility,
      confidenceScore: 0.82,
      keyTakeaways: [
        `Wind speeds of ${weatherData?.windSpeed ?? 'unknown'} mph will impact scoring`,
        `Average score: ${avgScore.toFixed(1)} (${avgScore > courseRating ? 'over par' : 'under par'})`,
        `Ownership concentration at ${ownershipConcentration}% suggests moderate chalk exposure`,
        `Field size of ${totalPlayers} players creates balanced slate conditions`,
      ],
      bestValue: {
        playerName: 'Sample Player',
        reason: 'Salary 24th vs projection rank 11th creates significant value premium',
        confidence: 0.88,
      },
      bestLeverage: {
        playerName: 'Sample Player 2',
        reason: 'Only 5% owned despite 45+ fantasy points projection',
        confidence: 0.85,
      },
      bestFade: {
        playerName: 'Sample Player 3',
        reason: '62% ownership with unclear historical course fit',
        confidence: 0.79,
      },
      bestCashPlay: {
        playerName: 'Sample Player 4',
        reason: 'Consistent top 20 finisher with favorable weather',
        confidence: 0.91,
      },
      bestGppPlay: {
        playerName: 'Sample Player 5',
        reason: 'High ceiling at reasonable salary; pivoting off chalk',
        confidence: 0.75,
      },
    }

    return Response.json({
      success: true,
      data: recommendations,
    })
  } catch (error) {
    console.error('[Analytics] Error:', error)
    return Response.json(
      { error: error instanceof Error ? error.message : 'Failed to fetch tournament summary' },
      { status: 500 }
    )
  }
}

function calculateVariance(values: number[]): number {
  const mean = values.reduce((a, b) => a + b, 0) / values.length
  const squaredDiffs = values.map((v) => Math.pow(v - mean, 2))
  return Math.sqrt(squaredDiffs.reduce((a, b) => a + b, 0) / values.length)
}
